#!/usr/bin/env python3
"""EXP0 controller (exp0d) - V1 wiring, gates G0-G7.

One process. Python standard library only (3.11+). Binds 127.0.0.1 only.

  ./exp0 start | stop | restart | status | logs | doctor        lifecycle (./exp0 is generated by ./setup.sh)
  python3 controller/exp0d.py run                                foreground (what `start` launches)
  python3 controller/exp0d.py init --role all-in-one [--port N]  (called by ./setup.sh)

Authority (FOUNDATION.md, CONTEXT_PASS_V1.md):
  operator  /v1/op/* on 127.0.0.1; bearer = ephemeral session key printed by `./exp0 start`
  opponent  Twitch whispers whose authenticated from_user_id == the resolved numeric id of the opponent
  chat      input only, never authority
Secrets: the Twitch user token lives in this process's memory only. Nothing secret is written to disk
except the ephemeral session key (var/session.key, mode 600, deleted on stop).
"""
from __future__ import annotations

import base64
import collections
import hashlib
import hmac
import http.server
import json
import os
import re
import secrets
import signal
import socket
import ssl
import struct
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

VERSION = "exp0-v1.0"
ROOT = Path(__file__).resolve().parent.parent
VAR = Path(os.environ.get("EXP0_VAR") or (ROOT / "var"))
CONFIG_PATH = VAR / "config.json"
STATE_PATH = VAR / "state.json"
HISTORY_PATH = VAR / "history.ndjson"
PID_PATH = VAR / "exp0d.pid"
KEY_PATH = VAR / "session.key"
LOG_PATH = VAR / "controller.log"

# Overridable only through the environment of the local operator (used by tests/). Never by a web page.
TWITCH_ID = os.environ.get("EXP0_TWITCH_ID_URL", "https://id.twitch.tv").rstrip("/")
TWITCH_HELIX = os.environ.get("EXP0_TWITCH_HELIX_URL", "https://api.twitch.tv/helix").rstrip("/")
TWITCH_EVENTSUB = os.environ.get("EXP0_TWITCH_EVENTSUB_URL", "wss://eventsub.wss.twitch.tv/ws")
ALLOWED_ORIGINS = {"https://raw.githack.com", "https://rawcdn.githack.com"}
ALLOWED_ORIGINS |= {o.strip() for o in os.environ.get("EXP0_EXTRA_ORIGINS", "").split(",") if o.strip()}

REQUIRED_SCOPES = ("user:read:chat", "user:write:chat", "user:manage:whispers")
PROTOCOL = 1
LOOPBACK_HOSTS = ("127.0.0.1", "localhost", "::1")

DEFAULT_CONFIG = {
    "role": "all-in-one",
    "port": 8787,
    "lmstudio_url": "http://127.0.0.1:1234",
    "opponent_login": "bigrigjay",
    "opponent_id": None,
    "opponent_display": None,
    "self_id": None,
    "self_login": None,
    "client_id": None,
    "permission": None,
    "ally_url": "https://raw.githack.com/NFDFLDTHRY/EXP0/main/ally.html",
    "village_url": "https://raw.githack.com/NFDFLDTHRY/EXP0/main/village.html",
    "limits": {
        "chat_min_interval_s": 3.0,
        "chat_max_per_min": 10,
        "repeat_window_s": 600,
        "whisper_min_interval_s": 1.0,
        "whisper_max_per_min": 60,
    },
}
DEFAULT_STATE = {"estop": False, "game": None, "seen": [], "executed": [], "whispered": []}


# ----------------------------------------------------------------------------------------------- helpers
def now_iso() -> str:
    t = time.time()
    return time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(t)) + ".%03dZ" % int((t % 1) * 1000)


def log(msg: str) -> None:
    sys.stderr.write(f"{now_iso()} {msg}\n")
    sys.stderr.flush()


def load_json(path: Path, default):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return default
    except (OSError, ValueError) as e:
        log(f"cannot read {path}: {e}")
        return default


def save_json(path: Path, obj, mode: int = 0o600) -> None:
    tmp = path.with_name(path.name + ".tmp")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=1, sort_keys=True)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


def merged(default: dict, loaded) -> dict:
    out = json.loads(json.dumps(default))
    if isinstance(loaded, dict):
        for k, v in loaded.items():
            if isinstance(out.get(k), dict) and isinstance(v, dict):
                out[k].update(v)
            else:
                out[k] = v
    return out


_DIRECT = urllib.request.build_opener(urllib.request.ProxyHandler({}))


def http_json(method: str, url: str, headers: dict | None = None, body=None, form: dict | None = None,
              timeout: float = 10.0):
    """Returns (status, obj). status 0 = network failure. Loopback URLs never go through a proxy."""
    h = {"Accept": "application/json", "User-Agent": "exp0/" + VERSION}
    if headers:
        h.update(headers)
    data = None
    if form is not None:
        data = urllib.parse.urlencode(form).encode()
        h["Content-Type"] = "application/x-www-form-urlencoded"
    elif body is not None:
        data = json.dumps(body).encode()
        h["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, method=method, headers=h)
    opener = _DIRECT if urllib.parse.urlsplit(url).hostname in LOOPBACK_HOSTS else urllib.request.build_opener()
    try:
        with opener.open(req, timeout=timeout) as r:
            status, raw = r.status, r.read()
    except urllib.error.HTTPError as e:
        status, raw = e.code, e.read()
    except (urllib.error.URLError, OSError, ValueError) as e:
        return 0, {"error": f"{type(e).__name__}: {e}"}
    if not raw:
        return status, {}
    try:
        obj = json.loads(raw)
        return status, obj if isinstance(obj, dict) else {"data": obj}
    except ValueError:
        return status, {"raw": raw[:300].decode("utf-8", "replace")}


def tw_validate(token: str):
    return http_json("GET", TWITCH_ID + "/oauth2/validate", {"Authorization": "OAuth " + token})


class ApiError(Exception):
    def __init__(self, status: int, error: str):
        super().__init__(error)
        self.status = status
        self.error = error


# ----------------------------------------------------------------------------------------------- history
class History:
    """APPEND-ONLY HISTORY: one NDJSON file, never rewritten. seq continues across restarts."""

    def __init__(self, path: Path):
        self.path = path
        self.lock = threading.Lock()
        self.ok = True
        self.seq = self._last_seq()

    def _last_seq(self) -> int:
        try:
            with open(self.path, "rb") as f:
                f.seek(0, 2)
                size = f.tell()
                f.seek(max(0, size - 65536))
                lines = f.read().splitlines()
        except FileNotFoundError:
            return 0
        for line in reversed(lines):
            try:
                return int(json.loads(line)["seq"])
            except (ValueError, KeyError, TypeError):
                continue
        return 0

    def append(self, kind: str, data: dict, ref: dict | None = None) -> int:
        with self.lock:
            self.seq += 1
            rec = {"seq": self.seq, "t": now_iso(), "kind": kind, "data": data}
            if ref:
                rec["ref"] = {k: v for k, v in ref.items() if v is not None}
            line = json.dumps(rec, separators=(",", ":"), ensure_ascii=False) + "\n"
            try:
                fd = os.open(self.path, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o600)
                with os.fdopen(fd, "a", encoding="utf-8") as f:
                    f.write(line)
                    f.flush()
                    os.fsync(f.fileno())
                self.ok = True
            except OSError as e:
                self.ok = False
                log(f"HISTORY WRITE FAILED: {e}")
            return self.seq

    def tail(self, after: int = 0, limit: int = 200) -> list:
        with self.lock:
            try:
                with open(self.path, "rb") as f:
                    f.seek(0, 2)
                    size = f.tell()
                    f.seek(max(0, size - 2_000_000))
                    data = f.read()
            except FileNotFoundError:
                return []
        out = []
        for line in data.splitlines():
            try:
                rec = json.loads(line)
            except ValueError:
                continue
            if isinstance(rec, dict) and rec.get("seq", 0) > after:
                out.append(rec)
        return out[-limit:]


# ----------------------------------------------------------------------------------------------- websocket
class WSClosed(Exception):
    def __init__(self, msg: str, code: int | None = None):
        super().__init__(msg)
        self.code = code


class WSClient:
    """Minimal RFC 6455 client (text/binary, fragmentation, ping/pong, close). Enough for EventSub."""

    GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"

    def __init__(self, url: str, timeout: float = 15.0):
        u = urllib.parse.urlsplit(url)
        if u.scheme not in ("ws", "wss") or not u.hostname:
            raise ValueError(f"not a websocket url: {url}")
        secure = u.scheme == "wss"
        port = u.port or (443 if secure else 80)
        path = (u.path or "/") + (("?" + u.query) if u.query else "")
        sock = socket.create_connection((u.hostname, port), timeout=timeout)
        if secure:
            sock = ssl.create_default_context().wrap_socket(sock, server_hostname=u.hostname)
        self.sock = sock
        self.buf = b""
        self.closed = False
        self.send_lock = threading.Lock()
        self.frag_op = None
        self.frag: list = []
        key = base64.b64encode(os.urandom(16)).decode()
        hostport = u.hostname if port == (443 if secure else 80) else f"{u.hostname}:{port}"
        req = (f"GET {path} HTTP/1.1\r\nHost: {hostport}\r\nUpgrade: websocket\r\nConnection: Upgrade\r\n"
               f"Sec-WebSocket-Key: {key}\r\nSec-WebSocket-Version: 13\r\nUser-Agent: exp0/{VERSION}\r\n\r\n")
        sock.sendall(req.encode("ascii"))
        while b"\r\n\r\n" not in self.buf:
            chunk = sock.recv(4096)
            if not chunk:
                raise WSClosed("eof during handshake", 1006)
            self.buf += chunk
            if len(self.buf) > 65536:
                raise WSClosed("handshake too large")
        head, _, self.buf = self.buf.partition(b"\r\n\r\n")
        lines = head.decode("latin-1").split("\r\n")
        parts = lines[0].split(" ", 2)
        if len(parts) < 2 or parts[1] != "101":
            raise WSClosed("handshake refused: " + lines[0])
        hdrs = {}
        for line in lines[1:]:
            if ":" in line:
                k, v = line.split(":", 1)
                hdrs[k.strip().lower()] = v.strip()
        accept = base64.b64encode(hashlib.sha1((key + self.GUID).encode()).digest()).decode()
        if hdrs.get("sec-websocket-accept") != accept:
            raise WSClosed("bad Sec-WebSocket-Accept")

    def _try_frame(self):
        b = self.buf
        if len(b) < 2:
            return None
        fin, opcode = b[0] & 0x80, b[0] & 0x0F
        masked, ln, i = b[1] & 0x80, b[1] & 0x7F, 2
        if ln == 126:
            if len(b) < 4:
                return None
            ln, i = struct.unpack(">H", b[2:4])[0], 4
        elif ln == 127:
            if len(b) < 10:
                return None
            ln, i = struct.unpack(">Q", b[2:10])[0], 10
        if ln > 16 * 1024 * 1024:
            raise WSClosed("frame too large", 1009)
        mask = None
        if masked:
            if len(b) < i + 4:
                return None
            mask, i = b[i:i + 4], i + 4
        if len(b) < i + ln:
            return None
        payload = b[i:i + ln]
        if mask:
            payload = bytes(x ^ mask[j % 4] for j, x in enumerate(payload))
        self.buf = b[i + ln:]
        return bool(fin), opcode, payload

    def recv(self, timeout: float):
        """(opcode, payload) of one complete message, or None on timeout."""
        deadline = time.monotonic() + timeout
        while True:
            fr = self._try_frame()
            if fr is None:
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    return None
                self.sock.settimeout(remaining)
                try:
                    chunk = self.sock.recv(65536)
                except (socket.timeout, TimeoutError):
                    return None
                if not chunk:
                    self.closed = True
                    raise WSClosed("connection lost", 1006)
                self.buf += chunk
                continue
            fin, op, payload = fr
            if op == 0x9:
                self._send(0xA, payload)
                continue
            if op == 0xA:
                continue
            if op == 0x8:
                code = struct.unpack(">H", payload[:2])[0] if len(payload) >= 2 else 1005
                reason = payload[2:].decode("utf-8", "replace")
                try:
                    self._send(0x8, payload[:2])
                except OSError:
                    pass
                self.closed = True
                try:
                    self.sock.close()
                except OSError:
                    pass
                raise WSClosed(f"closed by server: {code} {reason}".strip(), code)
            if op in (0x1, 0x2):
                if fin:
                    return op, payload
                self.frag_op, self.frag = op, [payload]
                continue
            if op == 0x0 and self.frag_op is not None:
                self.frag.append(payload)
                if fin:
                    op0, data = self.frag_op, b"".join(self.frag)
                    self.frag_op, self.frag = None, []
                    return op0, data
                continue
            raise WSClosed(f"protocol error: opcode {op}", 1002)

    def _send(self, opcode: int, payload: bytes = b"") -> None:
        header = bytearray([0x80 | opcode])
        n = len(payload)
        if n < 126:
            header.append(0x80 | n)
        elif n < 65536:
            header.append(0x80 | 126)
            header += struct.pack(">H", n)
        else:
            header.append(0x80 | 127)
            header += struct.pack(">Q", n)
        mask = os.urandom(4)
        header += mask
        body = bytes(x ^ mask[i % 4] for i, x in enumerate(payload))
        with self.send_lock:
            self.sock.settimeout(10)
            self.sock.sendall(bytes(header) + body)

    def close(self, code: int = 1000, reason: str = "") -> None:
        if self.closed:
            return
        self.closed = True
        try:
            self._send(0x8, struct.pack(">H", code) + reason.encode()[:120])
        except OSError:
            pass
        try:
            self.sock.close()
        except OSError:
            pass


# ----------------------------------------------------------------------------------------------- edge
class Edge:
    """TWITCH BOUNDARY: EventSub WebSocket session, subscriptions, reconnects. Terminates Twitch structures."""

    def __init__(self, c: "Controller"):
        self.c = c
        self.thread: threading.Thread | None = None
        self.stop_evt = threading.Event()
        self.connected = False
        self.session_id = None
        self.subs: dict = {}
        self.error = None
        self.last_msg = 0.0
        self.keepalive = 30
        self.ws: WSClient | None = None
        self.reconnects = 0
        self.session_ok = False

    def running(self) -> bool:
        return bool(self.thread and self.thread.is_alive())

    def start(self) -> bool:
        if self.running() and self.stop_evt.is_set():
            self.thread.join(5)  # a previous session is still winding down
        if self.running():
            return False
        self.stop_evt.clear()
        self.error = None
        self.reconnects = 0
        self.thread = threading.Thread(target=self._run, name="edge", daemon=True)
        self.thread.start()
        return True

    def stop(self, wait: bool = True) -> None:
        self.stop_evt.set()
        ws = self.ws
        if ws:
            ws.close(1000, "stop")
        if wait and self.thread and self.thread is not threading.current_thread():
            self.thread.join(5)
        self.connected = False

    def _run(self) -> None:
        c = self.c
        backoff = 1.0
        c.hist.append("session", {"op": "edge_start"})
        while not self.stop_evt.is_set():
            if not c.revalidate(max_age=0 if self.reconnects else 60):
                c.auth_invalid("token not valid at (re)connect")
                break
            self.session_ok = False
            url = TWITCH_EVENTSUB + ("&" if "?" in TWITCH_EVENTSUB else "?") + "keepalive_timeout_seconds=30"
            try:
                self._session(url)
            except WSClosed as e:
                self.error = str(e)
                c.hist.append("session", {"op": "ws_closed", "reason": str(e), "code": e.code})
            except (OSError, ValueError, KeyError, TypeError) as e:
                self.error = f"{type(e).__name__}: {e}"
                c.hist.append("session", {"op": "ws_error", "error": self.error})
            self.connected = False
            self.session_id = None
            for s in self.subs.values():
                if s.get("status") == "enabled":
                    s["status"] = "disconnected"
            if self.stop_evt.is_set():
                break
            if self.session_ok:
                backoff = 1.0
            self.reconnects += 1
            c.hist.append("session", {"op": "reconnect_scheduled", "in_s": backoff,
                                      "note": "external actions refused until the connection is valid again"})
            if self.stop_evt.wait(backoff):
                break
            backoff = min(backoff * 2, 60.0)
        self.connected = False
        c.hist.append("session", {"op": "edge_stopped"})

    def _expect_welcome(self, ws: WSClient) -> dict:
        deadline = time.time() + 15
        while time.time() < deadline and not self.stop_evt.is_set():
            m = ws.recv(1.0)
            if m is None:
                continue
            self.last_msg = time.time()
            msg = json.loads(m[1].decode("utf-8"))
            if (msg.get("metadata") or {}).get("message_type") == "session_welcome":
                return msg["payload"]["session"]
            self.c.hist.append("error", {"op": "unexpected_before_welcome", "message_type": (msg.get("metadata") or {}).get("message_type")})
        raise WSClosed("no session_welcome within 15s")

    def _session(self, url: str) -> None:
        c = self.c
        ws = WSClient(url)
        self.ws = ws
        try:
            w = self._expect_welcome(ws)
            self.session_id = w["id"]
            self.keepalive = int(w.get("keepalive_timeout_seconds") or 30)
            c.hist.append("session", {"op": "welcome", "session_id": self.session_id,
                                      "keepalive_timeout_seconds": self.keepalive})
            self._subscribe_all()
            enabled = [k for k, s in self.subs.items() if s.get("status") == "enabled"]
            if not enabled:
                raise WSClosed("no subscription was accepted")
            self.connected = True
            self.session_ok = True
            with c.lock:
                c.tests["eventsub"] = {"ok": True, "at": now_iso(), "session_id": self.session_id,
                                       "subs": {k: s.get("status") for k, s in self.subs.items()}}
            while not self.stop_evt.is_set():
                tok = c.token
                if not tok or not tok.get("valid"):
                    raise WSClosed("authentication invalid")
                if time.time() - self.last_msg > self.keepalive + 5:
                    c.hist.append("session", {"op": "keepalive_timeout", "silence_s": round(time.time() - self.last_msg, 1)})
                    raise WSClosed("keepalive timeout", 4005)
                m = ws.recv(1.0)
                if m is None:
                    continue
                self.last_msg = time.time()
                try:
                    msg = json.loads(m[1].decode("utf-8"))
                except ValueError:
                    c.hist.append("error", {"op": "unknown_input", "reason": "not json"})
                    continue
                t = (msg.get("metadata") or {}).get("message_type")
                if t == "session_keepalive":
                    continue
                if t == "notification":
                    c.on_notification(msg)
                elif t == "session_reconnect":
                    ws = self._reconnect(ws, msg)
                elif t == "revocation":
                    sub = (msg.get("payload") or {}).get("subscription") or {}
                    for s in self.subs.values():
                        if s.get("id") == sub.get("id"):
                            s["status"] = "revoked:" + str(sub.get("status"))
                    c.hist.append("session", {"op": "revocation", "subscription_id": sub.get("id"),
                                              "type": sub.get("type"), "status": sub.get("status")})
                    if not any(s.get("status") == "enabled" for s in self.subs.values()):
                        raise WSClosed("all subscriptions revoked")
                else:
                    c.hist.append("error", {"op": "unknown_input", "message_type": t, "note": "logged and ignored"})
        finally:
            ws.close(1000, "bye")
            self.ws = None

    def _subscribe_all(self) -> None:
        c = self.c
        tok = c.token or {}
        me = tok.get("user_id")
        scopes = tok.get("scopes") or []
        wanted = [("own_chat", "channel.chat.message", {"broadcaster_user_id": me, "user_id": me})]
        opp = c.config.get("opponent_id")
        if opp and opp != me:
            wanted.append(("opponent_chat", "channel.chat.message", {"broadcaster_user_id": opp, "user_id": me}))
        if "user:manage:whispers" in scopes or "user:read:whispers" in scopes:
            wanted.append(("whispers", "user.whisper.message", {"user_id": me}))
        subs = {}
        for key, typ, cond in wanted:
            body = {"type": typ, "version": "1", "condition": cond,
                    "transport": {"method": "websocket", "session_id": self.session_id}}
            st, b = c.helix("POST", "/eventsub/subscriptions", body)
            d = b.get("data")[0] if isinstance(b.get("data"), list) and b.get("data") else {}
            rec = {"type": typ, "condition": cond, "http": st, "id": d.get("id"),
                   "status": d.get("status") if st == 202 else "failed",
                   "error": None if st == 202 else (b.get("message") or b.get("error"))}
            subs[key] = rec
            c.hist.append("session", {"op": "subscribe", "key": key, **rec})
        self.subs = subs

    def _reconnect(self, old: WSClient, msg: dict) -> WSClient:
        c = self.c
        url = ((msg.get("payload") or {}).get("session") or {}).get("reconnect_url")
        c.hist.append("session", {"op": "reconnect_requested", "note": "old connection kept until the new one says welcome"})
        new = WSClient(url)
        w = self._expect_welcome(new)
        while True:  # drain what the old connection still delivered
            try:
                m = old.recv(0.2)
            except WSClosed:
                break
            if m is None:
                break
            try:
                om = json.loads(m[1].decode("utf-8"))
            except ValueError:
                continue
            if (om.get("metadata") or {}).get("message_type") == "notification":
                c.on_notification(om)
        old.close(1000, "reconnected")
        self.ws = new
        self.session_id = w["id"]
        self.keepalive = int(w.get("keepalive_timeout_seconds") or self.keepalive)
        c.hist.append("session", {"op": "reconnected", "session_id": self.session_id,
                                  "note": "subscriptions carried over by Twitch; not recreated"})
        return new


# ----------------------------------------------------------------------------------------------- controller
class Controller:
    def __init__(self):
        VAR.mkdir(parents=True, exist_ok=True)
        os.chmod(VAR, 0o700)
        self.lock = threading.RLock()
        self.config = merged(DEFAULT_CONFIG, load_json(CONFIG_PATH, {}))
        self.state = merged(DEFAULT_STATE, load_json(STATE_PATH, {}))
        self.hist = History(HISTORY_PATH)
        self.key = secrets.token_urlsafe(32)
        self.token: dict | None = None
        self.seen = collections.OrderedDict((k, True) for k in self.state.get("seen") or [])
        self.executed = collections.OrderedDict((k, True) for k in self.state.get("executed") or [])
        self.whispered = set(self.state.get("whispered") or [])
        self.chat_times: collections.deque = collections.deque()
        self.recent_texts: collections.deque = collections.deque()
        self.whisper_times: collections.deque = collections.deque()
        self.pending_echo: dict = {}
        self.self_seen: collections.OrderedDict = collections.OrderedDict()
        self.recent_chat: collections.deque = collections.deque(maxlen=12)
        self.recent_commands: collections.deque = collections.deque(maxlen=12)
        self.tests: dict = {"eventsub": None, "chat_read": None, "chat_send": None}
        self.lm = None
        self.dirty = False
        self.started = time.time()
        self.stopping = threading.Event()
        self.wq: collections.deque = collections.deque()
        self.wq_cv = threading.Condition()
        self.edge = Edge(self)
        threading.Thread(target=self._whisper_pump, name="whisper-pump", daemon=True).start()
        threading.Thread(target=self._housekeeping, name="housekeeping", daemon=True).start()
        self.hist.append("control", {"op": "controller_start", "version": VERSION, "role": self.config["role"],
                                     "pid": os.getpid(), "estop": bool(self.state.get("estop")),
                                     "game": (self.state.get("game") or {}).get("sid"),
                                     "note": "Twitch token is memory-only: authorize again in ally.html after every start"})

    # ---- persistence
    def save_state_locked(self) -> None:
        while len(self.seen) > 5000:
            self.seen.popitem(last=False)
        while len(self.executed) > 2000:
            self.executed.popitem(last=False)
        self.state["seen"] = list(self.seen.keys())
        self.state["executed"] = list(self.executed.keys())
        self.state["whispered"] = sorted(self.whispered)
        save_json(STATE_PATH, self.state)
        self.dirty = False

    def save_config(self) -> None:
        with self.lock:
            save_json(CONFIG_PATH, self.config)

    def _housekeeping(self) -> None:
        while not self.stopping.wait(2.0):
            with self.lock:
                if self.dirty:
                    self.save_state_locked()
            tok = self.token
            if tok and tok.get("valid") and time.time() - tok.get("validated_at", 0) > 3600:
                if not self.revalidate(max_age=3600):
                    self.auth_invalid("hourly validation failed")

    def close(self) -> None:
        self.stopping.set()
        with self.wq_cv:
            self.wq_cv.notify_all()
        self.edge.stop()
        with self.lock:
            self.save_state_locked()

    def mark_seen(self, *keys: str) -> bool:
        keys = tuple(k for k in keys if k and not k.endswith(":"))
        with self.lock:
            if any(k in self.seen for k in keys):
                return False
            for k in keys:
                self.seen[k] = True
            self.dirty = True
            return True

    # ---- twitch auth
    def helix(self, method: str, path: str, body=None):
        tok = self.token
        if not tok:
            raise ApiError(409, "no_twitch_token")
        st, b = http_json(method, TWITCH_HELIX + path,
                          {"Authorization": "Bearer " + tok["access_token"], "Client-Id": tok["client_id"]}, body)
        if st == 401:
            self.auth_invalid(f"helix {method} {path.split('?')[0]} returned 401")
        return st, b

    def revalidate(self, max_age: float = 3600) -> bool:
        tok = self.token
        if not tok:
            return False
        if tok.get("valid") and time.time() - tok.get("validated_at", 0) < max_age:
            return True
        st, v = tw_validate(tok["access_token"])
        if st == 200:
            with self.lock:
                tok.update(valid=True, validated_at=time.time(), expires_in=v.get("expires_in"),
                           scopes=v.get("scopes") or tok.get("scopes"))
            self.hist.append("session", {"op": "token_validated", "expires_in": v.get("expires_in")})
            return True
        if st == 401:
            with self.lock:
                tok["valid"] = False
            return False
        self.hist.append("error", {"op": "validate_unreachable", "http": st, "detail": v.get("error")})
        return bool(tok.get("valid"))

    def auth_invalid(self, why: str) -> None:
        with self.lock:
            already = self.token is not None and not self.token.get("valid")
            if self.token:
                self.token["valid"] = False
        if not already:
            self.hist.append("error", {"op": "invalid_authentication", "why": why,
                                       "action": "stop: no external actions until re-authorized in ally.html"})
        self.edge.stop(wait=False)

    def twitch_public(self) -> dict:
        t = self.token
        if not t:
            return {"token": False, "valid": False, "missing_scopes": list(REQUIRED_SCOPES)}
        return {"token": True, "valid": bool(t.get("valid")), "login": t.get("login"), "user_id": t.get("user_id"),
                "client_id": t.get("client_id"), "scopes": t.get("scopes"),
                "missing_scopes": [s for s in REQUIRED_SCOPES if s not in (t.get("scopes") or [])],
                "expires_in": t.get("expires_in"),
                "validated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(t.get("validated_at", 0)))}

    def set_client_id(self, client_id) -> dict:
        if not isinstance(client_id, str) or not re.fullmatch(r"[a-z0-9]{20,64}", client_id.strip()):
            raise ApiError(400, "bad_client_id")
        client_id = client_id.strip()
        with self.lock:
            changed = self.config.get("client_id") != client_id
            self.config["client_id"] = client_id
            if changed and self.token and self.token.get("client_id") != client_id:
                self.token = None
            self.save_config()
        if changed:
            self.edge.stop()
        self.hist.append("control", {"op": "client_id_saved", "client_id": client_id, "changed": changed})
        return {"client_id": client_id}

    def accept_token(self, access_token) -> dict:
        if not isinstance(access_token, str) or not re.fullmatch(r"[A-Za-z0-9]{10,200}", access_token):
            raise ApiError(400, "bad_token_format")
        st, v = tw_validate(access_token)
        if st == 401:
            self.hist.append("error", {"op": "token_rejected", "why": "twitch validate returned 401"})
            raise ApiError(401, "twitch_rejected_token")
        if st != 200:
            raise ApiError(502, f"twitch_validate_http_{st}")
        with self.lock:
            cid = self.config.get("client_id")
            if cid and v.get("client_id") != cid:
                self.hist.append("error", {"op": "token_rejected", "why": "issued to a different client id",
                                           "token_client_id": v.get("client_id")})
                raise ApiError(409, "token_issued_to_different_client_id")
            bound = self.config.get("self_id")
            game = self.state.get("game")
            if bound and v.get("user_id") != bound and game:
                self.hist.append("error", {"op": "token_rejected", "why": "wrong Twitch account for the active game",
                                           "expected_user_id": bound, "got_user_id": v.get("user_id"),
                                           "got_login": v.get("login")})
                raise ApiError(409, "wrong_twitch_account")
            if bound and v.get("user_id") != bound:
                self.config["self_id"] = None
                self.config["self_login"] = None
                self.hist.append("control", {"op": "identity_unbound", "previous_user_id": bound,
                                             "note": "a different account authorized; confirm identity again"})
            if not cid:
                self.config["client_id"] = v.get("client_id")
            self.token = {"access_token": access_token, "login": v.get("login"), "user_id": v.get("user_id"),
                          "client_id": v.get("client_id"), "scopes": v.get("scopes") or [],
                          "expires_in": v.get("expires_in"), "validated_at": time.time(), "valid": True}
            self.save_config()
        pub = self.twitch_public()
        self.hist.append("control", {"op": "token_accepted", "login": pub["login"], "user_id": pub["user_id"],
                                     "scopes": pub["scopes"], "missing_scopes": pub["missing_scopes"],
                                     "expires_in": pub["expires_in"], "note": "token itself is never logged"})
        return pub

    def forget_token(self, revoke: bool) -> dict:
        tok = self.token
        self.edge.stop()
        status = None
        if tok and revoke:
            status, _ = http_json("POST", TWITCH_ID + "/oauth2/revoke",
                                  form={"client_id": tok["client_id"], "token": tok["access_token"]})
        with self.lock:
            self.token = None
        self.hist.append("control", {"op": "token_forgotten", "revoked_at_twitch": bool(revoke), "http": status})
        return {"forgotten": True, "revoke_http": status}

    def confirm_identity(self) -> dict:
        with self.lock:
            t = self.token
            if not t or not t.get("valid"):
                raise ApiError(409, "no_valid_token")
            g = self.state.get("game")
            if g and g.get("self_id") and g["self_id"] != t["user_id"]:
                raise ApiError(409, "game_bound_to_other_account")
            self.config["self_id"] = t["user_id"]
            self.config["self_login"] = t["login"]
            self.save_config()
        self.hist.append("control", {"op": "identity_confirmed", "user_id": t["user_id"], "login": t["login"],
                                     "meaning": "this account is the public voice of the Gemma civilization"})
        return {"self_id": t["user_id"], "self_login": t["login"]}

    def resolve_opponent(self, login: str) -> dict:
        login = login.strip().lower()
        m = re.search(r"twitch\.tv/([a-z0-9_]{2,25})", login)
        if m:
            login = m.group(1)
        if not re.fullmatch(r"[a-z0-9_]{2,25}", login):
            raise ApiError(400, "bad_login")
        st, b = self.helix("GET", "/users?login=" + urllib.parse.quote(login))
        if st != 200:
            raise ApiError(502, f"helix_users_http_{st}")
        data = b.get("data") or []
        if not data:
            raise ApiError(404, "no_such_twitch_user")
        u = data[0]
        with self.lock:
            prev = self.config.get("opponent_id")
            self.config.update(opponent_login=u["login"], opponent_id=u["id"], opponent_display=u.get("display_name"))
            g = self.state.get("game")
            if g and g.get("opponent_id") != u["id"]:
                self.hist.append("control", {"op": "game_invalidated", "why": "opponent changed", "sid": g["sid"]})
                self.state["game"] = None
                self.save_state_locked()
            self.save_config()
        self.hist.append("control", {"op": "opponent_resolved", "login": u["login"], "id": u["id"],
                                     "display_name": u.get("display_name"), "previous_id": prev,
                                     "note": "authority = this numeric id, never the display name"})
        if self.edge.running() and prev != u["id"]:
            self.edge.stop()
            self.edge.start()
        return {"login": u["login"], "id": u["id"], "display_name": u.get("display_name")}

    def set_permission(self, granted: bool, statement: str) -> dict:
        statement = statement.strip()[:1000]
        if granted and len(statement) < 8:
            raise ApiError(400, "statement_required")
        rec = {"granted": bool(granted), "statement": statement, "channel_login": self.config.get("opponent_login"),
               "recorded_at": now_iso()}
        with self.lock:
            self.config["permission"] = rec
            self.save_config()
        self.hist.append("control", {"op": "permission_recorded" if granted else "permission_withdrawn", **rec})
        return rec

    def set_estop(self, on: bool) -> dict:
        with self.lock:
            self.state["estop"] = bool(on)
            dropped = 0
            if on:
                with self.wq_cv:
                    dropped = len(self.wq)
                    self.wq.clear()
            self.save_state_locked()
        self.hist.append("control", {"op": "emergency_stop" if on else "emergency_stop_cleared",
                                     **({"pending_discarded": dropped} if on else {})})
        return {"estop": bool(on)}

    def edge_start(self) -> dict:
        with self.lock:
            t = self.token
            if not t or not t.get("valid"):
                raise ApiError(409, "no_valid_token")
            if self.config.get("self_id") != t.get("user_id"):
                raise ApiError(409, "identity_not_confirmed")
        return {"started": self.edge.start()}

    def edge_stop(self) -> dict:
        self.edge.stop()
        self.hist.append("control", {"op": "edge_stop_by_operator"})
        return {"stopped": True}

    # ---- inbound: TWITCH BOUNDARY -> normalized events
    def on_notification(self, msg: dict) -> None:
        md = msg.get("metadata") or {}
        p = msg.get("payload") or {}
        st = md.get("subscription_type")
        if st == "channel.chat.message":
            self.on_chat(md, p.get("event") or {})
        elif st == "user.whisper.message":
            self.on_whisper(md, p.get("event") or {})
        else:
            self.hist.append("error", {"op": "unknown_input", "subscription_type": st, "note": "logged and ignored"})

    def on_chat(self, md: dict, e: dict) -> None:
        cfg = self.config
        me = (self.token or {}).get("user_id")
        ch = e.get("broadcaster_user_id")
        m = e.get("message") or {}
        ev = {"event_id": md.get("message_id"), "timestamp": md.get("message_timestamp"), "channel_id": ch,
              "channel_login": e.get("broadcaster_user_login"),
              "channel_role": "own" if ch == me else ("opponent" if ch == cfg.get("opponent_id") else "other"),
              "message_id": e.get("message_id"), "chatter_id": e.get("chatter_user_id"),
              "chatter_name": e.get("chatter_user_name"), "chatter_login": e.get("chatter_user_login"),
              "text": m.get("text") if isinstance(m.get("text"), str) else "",
              "structured_message_data": {"message_type": e.get("message_type"), "fragments": m.get("fragments") or [],
                                          "badges": e.get("badges") or [], "cheer": e.get("cheer"),
                                          "source_broadcaster_user_id": e.get("source_broadcaster_user_id")},
              "reply_context": e.get("reply"), "is_self": bool(me) and e.get("chatter_user_id") == me,
              "source": "twitch"}
        if not self.mark_seen("ws:" + str(ev["event_id"] or ""), "chat:" + str(ev["message_id"] or "")):
            self.hist.append("event", {"duplicate": True, "dropped": True, "event_id": ev["event_id"],
                                       "message_id": ev["message_id"]})
            return
        seq = self.hist.append("event", ev, {"event_id": ev["event_id"], "message_id": ev["message_id"]})
        with self.lock:
            self.recent_chat.append({"seq": seq, "t": ev["timestamp"], "channel_role": ev["channel_role"],
                                     "channel_login": ev["channel_login"], "chatter": ev["chatter_name"],
                                     "text": ev["text"][:300], "is_self": ev["is_self"]})
            if not (self.tests.get("chat_read") or {}).get("ok"):
                self.tests["chat_read"] = {"ok": True, "seq": seq, "at": now_iso(), "channel_role": ev["channel_role"],
                                           "channel_login": ev["channel_login"], "chatter": ev["chatter_name"],
                                           "text": ev["text"][:200]}
            if ev["is_self"] and ev["message_id"]:
                self.self_seen[ev["message_id"]] = (ev["event_id"], seq)
                while len(self.self_seen) > 200:
                    self.self_seen.popitem(last=False)
                pend = self.pending_echo.pop(ev["message_id"], None)
                if pend:
                    self._confirm_echo_locked(pend[0], pend[1], ev["message_id"], (ev["event_id"], seq))

    # ---- inbound: private command bus (Twitch whispers from the opponent)
    def on_whisper(self, md: dict, e: dict) -> None:
        wid = e.get("whisper_id")
        text = (e.get("whisper") or {}).get("text") or ""
        if not self.mark_seen("ws:" + str(md.get("message_id") or ""), "whisper:" + str(wid or "")):
            self.hist.append("command", {"duplicate_delivery": True, "dropped": True, "whisper_id": wid})
            return
        frm = e.get("from_user_id")
        ref = {"whisper_id": wid}
        self.hist.append("command", {"whisper_id": wid, "from_user_id": frm, "from_user_login": e.get("from_user_login"),
                                     "from_user_name": e.get("from_user_name"), "to_user_id": e.get("to_user_id"),
                                     "text": text[:1000]}, ref)
        reply = None
        with self.lock:
            game = self.state.get("game")

            def decide(admitted: bool, **kw):
                self.hist.append("admission", {"whisper_id": wid, "admitted": admitted, **kw}, ref)
                self.recent_commands.append({"t": now_iso(), "from": e.get("from_user_login"), "admitted": admitted,
                                             **{k: kw[k] for k in ("seq", "type", "reasons") if k in kw}})

            if self.state.get("estop"):
                decide(False, reasons=["emergency_stop"], note="not applied, not answered; the sender retries after clear")
                return
            if not game:
                decide(False, reasons=["no_game_session"], note="ignored, no reply")
                return
            if frm != game["opponent_id"]:
                decide(False, reasons=["unauthorized_sender"], claimed_name=e.get("from_user_name"),
                       note="authority is the authenticated numeric user id; display names are ignored; no reply")
                return
            try:
                env = json.loads(text)
            except ValueError:
                env = None
            base = {"exp0": PROTOCOL, "sid": game["sid"]}
            if not isinstance(env, dict) or env.get("exp0") != PROTOCOL:
                decide(False, reasons=["malformed_or_wrong_protocol"])
                reply = {**base, "ack": None, "ok": False, "error": "malformed_or_wrong_protocol"}
            elif env.get("sid") != game["sid"]:
                decide(False, reasons=["wrong_session"], got_sid=str(env.get("sid"))[:40])
                reply = {**base, "sid": str(env.get("sid"))[:40], "ack": env.get("seq"), "ok": False,
                         "error": "wrong_session"}
            else:
                seq, typ, last = env.get("seq"), env.get("type"), game["last_seq"]
                if not isinstance(seq, int) or isinstance(seq, bool) or seq < 0:
                    decide(False, reasons=["bad_seq"])
                    reply = {**base, "ack": None, "ok": False, "error": "bad_seq"}
                elif seq == 0:
                    first = not game.get("joined")
                    if first:
                        game["joined"] = {"at": now_iso(), "login": e.get("from_user_login"), "whisper_id": wid}
                    self.save_state_locked()
                    decide(True, seq=0, type="sync", first_join=first)
                    if first:
                        self.hist.append("control", {"op": "opponent_joined", "sid": game["sid"], "user_id": frm,
                                                     "login": e.get("from_user_login")}, ref)
                    reply = {**base, "ack": 0, "ok": True, "joined": True, "expect": last + 1}
                elif seq <= last:
                    cached = game["responses"].get(str(seq))
                    decide(False, seq=seq, type=typ, reasons=["duplicate_sequence"], last_seq=last,
                           note="not re-applied; cached ACK re-sent")
                    reply = dict(cached) if cached else {**base, "ack": seq, "ok": True}
                    reply["dup"] = True
                elif seq > last + 1:
                    decide(False, seq=seq, type=typ, reasons=["sequence_gap"], expect=last + 1)
                    reply = {**base, "ack": seq, "ok": False, "error": "sequence_gap", "expect": last + 1}
                else:
                    result = self.apply_command(typ, env.get("payload"))
                    ok = "error" not in result
                    game["last_seq"] = seq
                    resp = {**base, "ack": seq, "ok": ok}
                    resp.update({"result": result} if ok else {"error": result["error"]})
                    game["responses"][str(seq)] = resp
                    while len(game["responses"]) > 64:
                        del game["responses"][min(game["responses"], key=int)]
                    self.save_state_locked()  # persisted BEFORE the ACK leaves: a retry can never re-apply
                    decide(True, seq=seq, type=typ)
                    self.hist.append("applied", {"sid": game["sid"], "seq": seq, "type": typ, "ok": ok,
                                                 "result": result}, ref)
                    reply = resp
        if reply is not None:
            self.queue_whisper(frm, reply, wid)

    def apply_command(self, typ, payload) -> dict:
        if typ == "ping":
            return {"pong": True, "t": now_iso()}
        return {"error": "unknown_type"}

    # ---- outbound: ACTION GATE + TWITCH SENDER
    def gate_chat(self, p: dict) -> list:
        r = []
        cfg, L, tok = self.config, self.config["limits"], self.token
        if self.state.get("estop"):
            r.append("emergency_stop")
        if not tok or not tok.get("valid"):
            r.append("auth_invalid")
        elif "user:write:chat" not in (tok.get("scopes") or []):
            r.append("missing_scope:user:write:chat")
        if not cfg.get("self_id") or not tok or tok.get("user_id") != cfg.get("self_id"):
            r.append("identity_not_confirmed")
        if not self.edge.connected:
            r.append("connection_invalid")
        if not self.hist.ok:
            r.append("history_unavailable")
        if p["channel"] not in ("self", "opponent") or not p.get("broadcaster_id"):
            r.append("wrong_channel")
        if p["channel"] == "opponent" and not (cfg.get("permission") or {}).get("granted"):
            r.append("no_streamer_permission")
        m = p.get("message")
        if not isinstance(m, str) or not m.strip() or len(m) > 500 or re.search(r"[\x00-\x1f\x7f]", m):
            r.append("invalid_message")
        if p["source_key"] in self.executed:
            r.append("already_executed")
        now = time.time()
        while self.chat_times and now - self.chat_times[0] > 60:
            self.chat_times.popleft()
        if self.chat_times and now - self.chat_times[-1] < L["chat_min_interval_s"]:
            r.append("rate_min_interval")
        if len(self.chat_times) >= L["chat_max_per_min"]:
            r.append("rate_per_minute")
        while self.recent_texts and now - self.recent_texts[0][2] > L["repeat_window_s"]:
            self.recent_texts.popleft()
        norm = m.strip().lower() if isinstance(m, str) else ""
        if any(c == p["channel"] and t == norm for c, t, _ in self.recent_texts):
            r.append("repetition")
        return r

    def propose_chat(self, source: str, channel: str, message: str, reason: str, source_key: str,
                     test_slot: str | None = None) -> dict:
        pid = "p-" + secrets.token_hex(6)
        with self.lock:
            cfg, tok = self.config, self.token
            bid = cfg.get("self_id") if channel == "self" else cfg.get("opponent_id") if channel == "opponent" else None
            p = {"proposal_id": pid, "source": source, "action_type": "chat", "channel": channel,
                 "broadcaster_id": bid, "message": message, "reason": reason, "source_key": source_key}
            self.hist.append("proposal", p, {"proposal_id": pid})
            reasons = self.gate_chat(p)
            self.hist.append("admission", {"proposal_id": pid, "admitted": not reasons, "reasons": reasons},
                             {"proposal_id": pid})
            if reasons:
                if test_slot:
                    self.tests[test_slot] = {"ok": False, "at": now_iso(), "target": channel, "text": message,
                                             "admitted": False, "reasons": reasons}
                return {"proposal_id": pid, "admitted": False, "reasons": reasons}
            self.executed[source_key] = True
            now = time.time()
            self.chat_times.append(now)
            self.recent_texts.append((channel, message.strip().lower(), now))
            self.save_state_locked()  # executed before the network call: a crash can't cause a resend
        body = {"broadcaster_id": bid, "sender_id": tok["user_id"], "message": message}
        self.hist.append("action", {"proposal_id": pid, "method": "POST", "url": TWITCH_HELIX + "/chat/messages",
                                    "body": body}, {"proposal_id": pid})
        st, b = self.helix("POST", "/chat/messages", body)
        d = b.get("data")[0] if isinstance(b.get("data"), list) and b.get("data") else {}
        res = {"proposal_id": pid, "http": st, "message_id": d.get("message_id"), "is_sent": d.get("is_sent"),
               "drop_reason": d.get("drop_reason"), "error": None if st == 200 else (b.get("message") or b.get("error"))}
        self.hist.append("result", res, {"proposal_id": pid})
        with self.lock:
            if test_slot:
                self.tests[test_slot] = {"ok": False, "at": now_iso(), "target": channel, "text": message,
                                         "admitted": True, "http": st, "is_sent": d.get("is_sent"),
                                         "message_id": d.get("message_id"), "drop_reason": d.get("drop_reason"),
                                         "error": res["error"], "echo": False}
            mid = d.get("message_id")
            if d.get("is_sent") and mid:
                if mid in self.self_seen:  # the echo outran the HTTP response
                    self._confirm_echo_locked(pid, test_slot, mid, self.self_seen[mid])
                else:
                    self.pending_echo[mid] = (pid, test_slot)
        return {"admitted": True, **res}

    def _confirm_echo_locked(self, pid: str, slot, mid: str, evt: tuple) -> None:
        self.hist.append("result", {"proposal_id": pid, "confirmed_by_event": evt[0], "event_seq": evt[1],
                                    "message_id": mid, "note": "our message observed in chat"}, {"proposal_id": pid})
        cs = self.tests.get(slot) if slot else None
        if cs and cs.get("message_id") == mid:
            cs.update(echo=True, echo_seq=evt[1], ok=bool(cs.get("is_sent")))

    def test_send(self, target: str) -> dict:
        if target not in ("self", "opponent"):
            raise ApiError(400, "bad_target")
        msg = f"EXP0 TEST {time.strftime('%H:%M:%S', time.gmtime())}Z #{secrets.token_hex(2)} (wiring test)"
        return self.propose_chat("operator_test", target, msg, "operator pressed 'send TEST message'",
                                 "test:" + secrets.token_hex(8), test_slot="chat_send")

    def queue_whisper(self, to_user_id: str, obj: dict, cause) -> None:
        with self.wq_cv:
            self.wq.append({"to": to_user_id, "message": json.dumps(obj, separators=(",", ":")), "cause": cause})
            self.wq_cv.notify()

    def _whisper_pump(self) -> None:
        while not self.stopping.is_set():
            with self.wq_cv:
                while not self.wq and not self.stopping.is_set():
                    self.wq_cv.wait(1.0)
                if self.stopping.is_set():
                    return
            L, now = self.config["limits"], time.time()
            while self.whisper_times and now - self.whisper_times[0] > 60:
                self.whisper_times.popleft()
            wait = 0.0
            if self.whisper_times:
                wait = max(wait, L["whisper_min_interval_s"] - (now - self.whisper_times[-1]))
            if len(self.whisper_times) >= L["whisper_max_per_min"]:
                wait = max(wait, 60 - (now - self.whisper_times[0]))
            if wait > 0:
                time.sleep(min(wait, 1.0))
                continue
            with self.wq_cv:
                if not self.wq:
                    continue
                item = self.wq.popleft()
            try:
                self._send_whisper(item)
            except Exception as ex:  # a failed send must never kill the pump
                self.hist.append("error", {"op": "whisper_send_exception", "error": f"{type(ex).__name__}: {ex}"})

    def _send_whisper(self, item: dict) -> None:
        pid = "w-" + secrets.token_hex(6)
        to, msg = item["to"], item["message"]
        ref = {"proposal_id": pid, "whisper_id": item.get("cause")}
        with self.lock:
            tok, game = self.token, self.state.get("game")
            self.hist.append("proposal", {"proposal_id": pid, "source": "command_bus", "action_type": "whisper",
                                          "to_user_id": to, "message": msg,
                                          "reason": f"reply to whisper {item.get('cause')}"}, ref)
            r = []
            if self.state.get("estop"):
                r.append("emergency_stop")
            if not tok or not tok.get("valid"):
                r.append("auth_invalid")
            elif "user:manage:whispers" not in (tok.get("scopes") or []):
                r.append("missing_scope:user:manage:whispers")
            if not game or to != game.get("opponent_id"):
                r.append("recipient_is_not_the_opponent")
            limit = 10000 if to in self.whispered else 500
            if len(msg) > limit:
                r.append(f"too_long_for_recipient:{limit}")
            if not self.hist.ok:
                r.append("history_unavailable")
            self.hist.append("admission", {"proposal_id": pid, "admitted": not r, "reasons": r}, ref)
            if r:
                return
            self.whisper_times.append(time.time())
        path = f"/whispers?from_user_id={urllib.parse.quote(tok['user_id'])}&to_user_id={urllib.parse.quote(to)}"
        self.hist.append("action", {"proposal_id": pid, "method": "POST", "url": TWITCH_HELIX + path,
                                    "body": {"message": msg}}, ref)
        st, b = self.helix("POST", path, {"message": msg})
        self.hist.append("result", {"proposal_id": pid, "http": st,
                                    "error": None if st == 204 else (b.get("message") or b.get("error")),
                                    "note": "204 = accepted; Twitch may still drop silently. Delivery is proven only by the peer."},
                         ref)
        if st == 204:
            with self.lock:
                self.whispered.add(to)
                self.dirty = True

    # ---- game session (command bus only at this gate)
    def new_game(self) -> dict:
        with self.lock:
            cfg = self.config
            for k, err in (("client_id", "no_client_id"), ("self_id", "identity_not_confirmed"),
                           ("opponent_id", "opponent_not_resolved")):
                if not cfg.get(k):
                    raise ApiError(409, err)
            prev = self.state.get("game")
            sid = secrets.token_hex(4)
            self.state["game"] = {"sid": sid, "created_at": now_iso(), "opponent_id": cfg["opponent_id"],
                                  "opponent_login": cfg["opponent_login"], "self_id": cfg["self_id"],
                                  "self_login": cfg.get("self_login"), "last_seq": 0, "joined": None, "responses": {}}
            self.save_state_locked()
        self.hist.append("control", {"op": "game_session_created", "sid": sid, "opponent_id": cfg["opponent_id"],
                                     "replaced_sid": prev["sid"] if prev else None})
        return self.game_public()

    def game_public(self):
        g = self.state.get("game")
        if not g:
            return None
        frag = urllib.parse.urlencode({"c": self.config.get("client_id") or "", "e": g["self_id"],
                                       "el": g.get("self_login") or "", "s": g["sid"], "o": g.get("opponent_login") or ""})
        return {"sid": g["sid"], "created_at": g["created_at"], "opponent_id": g["opponent_id"],
                "opponent_login": g.get("opponent_login"), "self_id": g["self_id"], "last_seq": g["last_seq"],
                "joined": g.get("joined"), "invite": self.config["village_url"] + "#" + frag}

    # ---- LM Studio (G7): reachability only; it must stay on loopback
    def lm_probe(self) -> dict:
        res = lm_check(self.config["lmstudio_url"])
        with self.lock:
            self.lm = res
        self.hist.append("session", {"op": "lmstudio_probe", **res})
        return res

    # ---- status
    def status(self) -> dict:
        with self.lock:
            cfg = self.config
            with self.wq_cv:
                qlen = len(self.wq)
            return {
                "exp0": VERSION, "role": cfg["role"], "pid": os.getpid(), "uptime_s": int(time.time() - self.started),
                "estop": bool(self.state.get("estop")),
                "config": {k: cfg.get(k) for k in ("port", "client_id", "opponent_login", "opponent_id",
                                                   "opponent_display", "self_id", "self_login", "permission",
                                                   "ally_url", "village_url", "lmstudio_url", "limits")},
                "required_scopes": list(REQUIRED_SCOPES),
                "twitch": self.twitch_public(),
                "edge": {"running": self.edge.running(), "connected": self.edge.connected,
                         "session_id": self.edge.session_id, "subs": self.edge.subs, "error": self.edge.error,
                         "reconnects": self.edge.reconnects,
                         "last_msg_age_s": round(time.time() - self.edge.last_msg, 1) if self.edge.last_msg else None},
                "tests": self.tests,
                "game": self.game_public(),
                "recent_chat": list(self.recent_chat),
                "recent_commands": list(self.recent_commands),
                "whisper_queue": qlen,
                "history": {"seq": self.hist.seq, "ok": self.hist.ok},
                "lmstudio": self.lm,
            }


def lm_check(base: str) -> dict:
    host = urllib.parse.urlsplit(base).hostname or ""
    if host not in LOOPBACK_HOSTS:
        return {"reachable": False, "models": [], "error": "lmstudio_url must be a loopback address (127.0.0.1)",
                "url": base, "checked_at": now_iso()}
    st, obj = http_json("GET", base.rstrip("/") + "/v1/models", timeout=3)
    data = obj.get("data") if isinstance(obj.get("data"), list) else None
    ok = st == 200 and data is not None
    return {"reachable": ok, "http": st, "url": base, "checked_at": now_iso(),
            "models": [m.get("id") for m in data if isinstance(m, dict)] if ok else [],
            "error": None if ok else (obj.get("error") or f"HTTP {st}")}


# ----------------------------------------------------------------------------------------------- loopback API
ROUTES = {
    ("GET", "/v1/status"): lambda c, b, q: c.status(),
    ("GET", "/v1/history"): lambda c, b, q: {"records": c.hist.tail(int((q.get("after") or ["0"])[0]),
                                                                     min(int((q.get("limit") or ["200"])[0]), 500))},
    ("POST", "/v1/op/client_id"): lambda c, b, q: c.set_client_id(b.get("client_id")),
    ("POST", "/v1/op/twitch/token"): lambda c, b, q: c.accept_token(b.get("access_token")),
    ("POST", "/v1/op/twitch/forget"): lambda c, b, q: c.forget_token(bool(b.get("revoke"))),
    ("POST", "/v1/op/identity/confirm"): lambda c, b, q: c.confirm_identity(),
    ("POST", "/v1/op/opponent"): lambda c, b, q: c.resolve_opponent(str(b.get("login") or "")),
    ("POST", "/v1/op/permission"): lambda c, b, q: c.set_permission(bool(b.get("granted")), str(b.get("statement") or "")),
    ("POST", "/v1/op/edge/start"): lambda c, b, q: c.edge_start(),
    ("POST", "/v1/op/edge/stop"): lambda c, b, q: c.edge_stop(),
    ("POST", "/v1/op/test/send"): lambda c, b, q: c.test_send(str(b.get("target") or "self")),
    ("POST", "/v1/op/estop"): lambda c, b, q: c.set_estop(True),
    ("POST", "/v1/op/estop/clear"): lambda c, b, q: c.set_estop(False),
    ("POST", "/v1/op/game/new"): lambda c, b, q: c.new_game(),
    ("POST", "/v1/op/lmstudio/probe"): lambda c, b, q: c.lm_probe(),
}


def make_handler(ctrl: Controller):
    port = ctrl.config["port"]
    hosts = {f"127.0.0.1:{port}", f"localhost:{port}", f"[::1]:{port}"}

    class Handler(http.server.BaseHTTPRequestHandler):
        server_version = "exp0d"
        sys_version = ""
        protocol_version = "HTTP/1.1"

        def log_message(self, *args):
            pass

        def _reply(self, status: int, obj: dict, origin: str | None = None) -> None:
            body = json.dumps(obj).encode()
            self.send_response(status)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.send_header("X-Content-Type-Options", "nosniff")
            if origin:
                self.send_header("Access-Control-Allow-Origin", origin)
                self.send_header("Vary", "Origin")
            self.end_headers()
            self.wfile.write(body)

        def _check(self):
            if self.headers.get("Host", "") not in hosts:
                return None, (403, {"error": "bad_host"})
            origin = self.headers.get("Origin")
            if origin is not None and origin not in ALLOWED_ORIGINS:
                return None, (403, {"error": "origin_not_allowed"})
            return origin, None

        def do_OPTIONS(self):
            origin, err = self._check()
            if err or not origin:
                self.send_response(403)
                self.send_header("Content-Length", "0")
                self.end_headers()
                return
            self.send_response(204)
            self.send_header("Access-Control-Allow-Origin", origin)
            self.send_header("Vary", "Origin")
            self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
            self.send_header("Access-Control-Allow-Headers", "Authorization, Content-Type")
            self.send_header("Access-Control-Max-Age", "600")
            if self.headers.get("Access-Control-Request-Private-Network") == "true":
                self.send_header("Access-Control-Allow-Private-Network", "true")
            self.send_header("Content-Length", "0")
            self.end_headers()

        def _handle(self, method: str) -> None:
            n = int(self.headers.get("Content-Length") or 0)
            if n > 65536:
                self.close_connection = True
                return self._reply(413, {"error": "too_large"})
            raw = self.rfile.read(n) if n else b""
            origin, err = self._check()
            if err:
                return self._reply(*err)
            u = urllib.parse.urlsplit(self.path)
            if method == "GET" and u.path == "/v1/health":
                return self._reply(200, {"ok": True, "exp0": VERSION, "role": ctrl.config["role"]}, origin)
            auth = self.headers.get("Authorization", "")
            if not (auth.startswith("Bearer ") and hmac.compare_digest(auth[7:].encode(), ctrl.key.encode())):
                return self._reply(401, {"error": "bad_session_key",
                                         "hint": "open the ally link printed by ./exp0 start or ./exp0 status"}, origin)
            try:
                body = json.loads(raw) if raw else {}
            except ValueError:
                return self._reply(400, {"error": "bad_json"}, origin)
            if not isinstance(body, dict):
                return self._reply(400, {"error": "bad_json"}, origin)
            fn = ROUTES.get((method, u.path))
            if not fn:
                return self._reply(404, {"error": "no_route"}, origin)
            try:
                return self._reply(200, fn(ctrl, body, urllib.parse.parse_qs(u.query)) or {"ok": True}, origin)
            except ApiError as e:
                return self._reply(e.status, {"error": e.error}, origin)
            except Exception as e:
                ctrl.hist.append("error", {"op": "api_exception", "path": u.path, "error": f"{type(e).__name__}: {e}"})
                return self._reply(500, {"error": "internal", "detail": str(e)[:200]}, origin)

        def do_GET(self):
            self._handle("GET")

        def do_POST(self):
            self._handle("POST")

    return Handler


class Server(http.server.ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True


# ----------------------------------------------------------------------------------------------- lifecycle
def read_config() -> dict:
    return merged(DEFAULT_CONFIG, load_json(CONFIG_PATH, {}))


def running_pid():
    try:
        pid = int(PID_PATH.read_text().strip())
    except (OSError, ValueError):
        return None
    try:
        os.kill(pid, 0)
    except OSError:
        return None
    try:
        cmd = Path(f"/proc/{pid}/cmdline").read_bytes().split(b"\0")
        if not any(p.endswith(b"exp0d.py") for p in cmd) or b"run" not in cmd:
            return None
    except OSError:
        pass
    return pid


def local_get(port: int, path: str, key: str | None = None, timeout: float = 3.0):
    h = {"Authorization": "Bearer " + key} if key else {}
    return http_json("GET", f"http://127.0.0.1:{port}{path}", h, timeout=timeout)


def ally_link(cfg: dict, key: str) -> str:
    return f"{cfg['ally_url']}#p={cfg['port']}&k={key}"


def cmd_init(argv: list) -> int:
    role, port = "all-in-one", None
    it = iter(argv)
    for a in it:
        if a == "--role":
            role = next(it, role)
        elif a == "--port":
            port = int(next(it))
    VAR.mkdir(parents=True, exist_ok=True)
    os.chmod(VAR, 0o700)
    cfg = read_config()
    cfg["role"] = role
    if port:
        if not 1024 <= port <= 65535:
            print("  FAIL  port must be 1024-65535")
            return 2
        cfg["port"] = port
    save_json(CONFIG_PATH, cfg)
    print(f"  PASS  config: {CONFIG_PATH} (role {role}, port {cfg['port']}, opponent {cfg['opponent_login']})")
    return 0


def cmd_run() -> int:
    VAR.mkdir(parents=True, exist_ok=True)
    os.chmod(VAR, 0o700)
    c = Controller()
    port = c.config["port"]
    try:
        srv = Server(("127.0.0.1", port), make_handler(c))
    except OSError as e:
        c.hist.append("error", {"op": "bind_failed", "port": port, "error": str(e)})
        log(f"cannot bind 127.0.0.1:{port}: {e}")
        c.close()
        return 2
    fd = os.open(KEY_PATH, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    os.write(fd, c.key.encode())
    os.close(fd)
    PID_PATH.write_text(str(os.getpid()))

    def on_signal(signum, _frame):
        c.hist.append("control", {"op": "controller_stop", "signal": signum})
        threading.Thread(target=srv.shutdown, daemon=True).start()

    signal.signal(signal.SIGTERM, on_signal)
    signal.signal(signal.SIGINT, on_signal)
    log(f"exp0d {VERSION} listening on 127.0.0.1:{port} (loopback only)")
    try:
        srv.serve_forever(poll_interval=0.5)
    finally:
        c.close()
        srv.server_close()
        for p in (KEY_PATH, PID_PATH):
            try:
                p.unlink()
            except OSError:
                pass
        log("exp0d stopped")
    return 0


def port_in_use(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.5)
        return s.connect_ex(("127.0.0.1", port)) == 0


def cmd_start() -> int:
    if not CONFIG_PATH.exists():
        print("not set up: run ./setup.sh first")
        return 2
    cfg = read_config()
    pid = running_pid()
    if pid:
        print(f"already running (pid {pid})")
        return cmd_status()
    if port_in_use(cfg["port"]):
        print(f"port {cfg['port']} on 127.0.0.1 is used by another program. Pick another: ./setup.sh --port N")
        return 2
    for p in (KEY_PATH, PID_PATH):
        try:
            p.unlink()
        except OSError:
            pass
    logf = open(LOG_PATH, "ab")
    proc = subprocess.Popen([sys.executable, str(Path(__file__).resolve()), "run"], cwd=str(ROOT),
                            stdin=subprocess.DEVNULL, stdout=logf, stderr=logf, start_new_session=True)
    deadline = time.time() + 10
    while time.time() < deadline:
        if proc.poll() is not None:
            print("controller exited during start - see ./exp0 logs")
            return 1
        if KEY_PATH.exists() and local_get(cfg["port"], "/v1/health", timeout=0.5)[0] == 200:
            break
        time.sleep(0.1)
    else:
        print("controller did not become healthy within 10s - see ./exp0 logs")
        return 1
    key = KEY_PATH.read_text().strip()
    print(f"EXP0 controller running: 127.0.0.1:{cfg['port']} (loopback only), pid {proc.pid}, role {cfg['role']}")
    print("Open ally.html with this link (everything after # stays in your browser):")
    print("  " + ally_link(cfg, key))
    return 0


def cmd_stop() -> int:
    pid = running_pid()
    if not pid:
        print("not running")
        return 0
    os.kill(pid, signal.SIGTERM)
    deadline = time.time() + 10
    while time.time() < deadline:
        try:
            os.kill(pid, 0)
        except OSError:
            print(f"stopped (pid {pid})")
            return 0
        time.sleep(0.1)
    os.kill(pid, signal.SIGKILL)
    print(f"killed (pid {pid}) after 10s")
    return 0


def cmd_status() -> int:
    cfg = read_config()
    pid = running_pid()
    if not pid:
        print("STOPPED (./exp0 start)")
        return 3
    try:
        key = KEY_PATH.read_text().strip()
    except OSError:
        key = ""
    st, s = local_get(cfg["port"], "/v1/status", key)
    if st != 200:
        print(f"RUNNING pid {pid} but the API did not answer (HTTP {st}) - see ./exp0 logs")
        return 1
    tw, ed, g, lm = s["twitch"], s["edge"], s["game"], s["lmstudio"]
    print(f"RUNNING  pid {pid}  127.0.0.1:{cfg['port']}  role {s['role']}  uptime {s['uptime_s']}s"
          + ("  E-STOP" if s["estop"] else ""))
    print(f"  twitch   {'valid' if tw['valid'] else ('INVALID' if tw['token'] else 'no token')}"
          + (f"  {tw['login']} ({tw['user_id']})  missing scopes: {tw['missing_scopes'] or 'none'}" if tw["token"] else "  (authorize in ally.html)"))
    print(f"  opponent {s['config']['opponent_login']} ({s['config']['opponent_id'] or 'unresolved'})")
    print(f"  edge     {'connected' if ed['connected'] else ('running, not connected' if ed['running'] else 'stopped')}"
          + "".join(f"  {k}:{v.get('status')}" for k, v in (ed["subs"] or {}).items()))
    t = s["tests"]
    print("  tests    " + "  ".join(f"{k}:{'ok' if (t.get(k) or {}).get('ok') else '-'}" for k in ("eventsub", "chat_read", "chat_send")))
    print(f"  game     {('sid ' + g['sid'] + '  last_seq ' + str(g['last_seq']) + ('  joined' if g['joined'] else '  not joined')) if g else 'none'}")
    print(f"  lmstudio {('reachable ' + ', '.join(lm['models'])) if lm and lm.get('reachable') else ('unreachable' if lm else 'not probed')}")
    print(f"  history  seq {s['history']['seq']}{'' if s['history']['ok'] else '  WRITE FAILING'}")
    print("  ally     " + ally_link(cfg, key))
    return 0


def cmd_logs() -> int:
    for p in (LOG_PATH, HISTORY_PATH):
        p.touch(exist_ok=True)
    os.execvp("tail", ["tail", "-n", "40", "-F", str(LOG_PATH), str(HISTORY_PATH)])
    return 0


def lan_ip():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("192.0.2.1", 9))
        ip = s.getsockname()[0]
        s.close()
        return None if ip.startswith("127.") else ip
    except OSError:
        return None


def tcp_open(host: str, port: int, timeout: float = 0.7) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def twitch_reach() -> list:
    """Real round trips, not just TCP/TLS (a filtering proxy can complete TLS and still block).
    Twitch must answer in its own words: 401 JSON without a token, and a session_welcome on EventSub."""
    out = []
    st, b = http_json("GET", TWITCH_ID + "/oauth2/validate")
    out.append((st == 401 and b.get("status") == 401, f"{TWITCH_ID} answers (HTTP {st}{': ' + str(b.get('raw') or b.get('error') or '')[:90] if st != 401 else ', 401 without a token as expected'})"))
    st, b = http_json("GET", TWITCH_HELIX + "/users?login=twitch")
    out.append((st == 401 and "error" in b, f"{TWITCH_HELIX} answers (HTTP {st}{': ' + str(b.get('raw') or b.get('error') or '')[:90] if st != 401 else ', 401 without a token as expected'})"))
    try:
        ws = WSClient(TWITCH_EVENTSUB + ("&" if "?" in TWITCH_EVENTSUB else "?") + "keepalive_timeout_seconds=10", timeout=8)
        try:
            m = ws.recv(8)
            msg = json.loads(m[1]) if m else {}
            ok = (msg.get("metadata") or {}).get("message_type") == "session_welcome"
            out.append((ok, f"{TWITCH_EVENTSUB} " + ("sent session_welcome" if ok else "connected but no welcome within 8s")))
        finally:
            ws.close(1000, "doctor")
    except (OSError, WSClosed, ValueError) as e:
        out.append((False, f"{TWITCH_EVENTSUB} ({type(e).__name__}: {e})"))
    return out


def cmd_doctor() -> int:
    fails = 0

    def line(level: str, msg: str) -> None:
        nonlocal fails
        fails += level == "FAIL"
        print(f"  {level:<4}  {msg}")

    print("EXP0 doctor")
    v = sys.version_info
    line("PASS" if v >= (3, 11) else "FAIL", f"python {v.major}.{v.minor}.{v.micro}")
    if not CONFIG_PATH.exists():
        line("FAIL", "not set up: run ./setup.sh")
        return 1
    cfg = read_config()
    line("PASS", f"setup: role {cfg['role']}, config {CONFIG_PATH}")
    mode = VAR.stat().st_mode & 0o777
    line("PASS" if mode == 0o700 else "WARN", f"var/ permissions {oct(mode)} (want 0o700)")
    tracked = subprocess.run(["git", "-C", str(ROOT), "ls-files", "--", "var"], capture_output=True, text=True)
    if tracked.returncode == 0:
        line("PASS" if not tracked.stdout.strip() else "FAIL", "no local state or secrets tracked by git (var/ ignored)")
    pid = running_pid()
    key = KEY_PATH.read_text().strip() if KEY_PATH.exists() else ""
    s = None
    if pid and local_get(cfg["port"], "/v1/health")[0] == 200:
        line("PASS", f"controller running, pid {pid}, 127.0.0.1:{cfg['port']}")
        st, s = local_get(cfg["port"], "/v1/status", key)
        if st != 200:
            s = None
        ip = lan_ip()
        if ip:
            line("FAIL" if tcp_open(ip, cfg["port"]) else "PASS",
                 f"controller not reachable from the network ({ip}:{cfg['port']} {'OPEN' if tcp_open(ip, cfg['port']) else 'closed'})")
    else:
        line("FAIL", "controller not running (./exp0 start)")
    for ok, why in twitch_reach():
        line("PASS" if ok else "FAIL", why)
    st, b = http_json("GET", cfg["ally_url"], timeout=8)
    gh_ok = st == 200 and "EXP0 / ALLY" in str(b.get("raw", ""))
    line("PASS" if gh_ok else "WARN", f"{cfg['ally_url']} (HTTP {st}{'' if gh_ok else ': ' + str(b.get('raw') or b.get('error') or '')[:90]})")
    if s:
        tw = s["twitch"]
        if tw["valid"]:
            line("PASS" if not tw["missing_scopes"] else "WARN",
                 f"twitch token valid: {tw['login']} ({tw['user_id']}), missing scopes: {tw['missing_scopes'] or 'none'}")
        else:
            line("WARN", "twitch not authorized in this controller run (ally.html -> Authorize)")
        line("PASS" if s["config"]["opponent_id"] else "WARN",
             f"opponent {s['config']['opponent_login']} -> {s['config']['opponent_id'] or 'unresolved'}")
        line("PASS" if s["edge"]["connected"] else "WARN", "EventSub edge " + ("connected" if s["edge"]["connected"] else "not connected"))
        if s["estop"]:
            line("WARN", "E-STOP is set")
    lm = lm_check(cfg["lmstudio_url"])
    line("PASS" if lm["reachable"] else "FAIL",
         f"LM Studio {cfg['lmstudio_url']}: " + (("models: " + ", ".join(lm["models"])) if lm["reachable"] else lm["error"]))
    ip = lan_ip()
    port = urllib.parse.urlsplit(cfg["lmstudio_url"]).port or 1234
    if ip:
        exposed = tcp_open(ip, port)
        line("FAIL" if exposed else "PASS",
             f"LM Studio not reachable from the network ({ip}:{port} {'OPEN - turn off Serve on Local Network' if exposed else 'closed'})")
    print(f"{'OK' if not fails else str(fails) + ' FAIL'}")
    return 1 if fails else 0


def main(argv: list) -> int:
    cmd = argv[1] if len(argv) > 1 else ""
    if cmd == "run":
        return cmd_run()
    if cmd == "init":
        return cmd_init(argv[2:])
    if cmd == "start":
        return cmd_start()
    if cmd == "stop":
        return cmd_stop()
    if cmd == "restart":
        cmd_stop()
        return cmd_start()
    if cmd == "status":
        return cmd_status()
    if cmd == "logs":
        return cmd_logs()
    if cmd == "doctor":
        return cmd_doctor()
    print("usage: ./exp0 start|stop|restart|status|logs|doctor")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
